development:
  adapter: postgresql
  host: localhost
  port: 5432
  database: cancan_devise_development
  encoding: utf8
  username: rails
  password: marm0t
  template: template0
  schema_search_path: public

test:
  adapter: postgresql
  host: localhost
  port: 5432
  database: cancan_devise_test
  encoding: utf8
  username: rails
  password: marm0t
  template: template0
  schema_search_path: public

production:
  adapter: postgresql
  host: localhost
  port: 5432
  database: cancan_devise_production
  encoding: utf8
  username: rails
  password: marm0t
  template: template0
  schema_search_path: public
